### ISSUE TITLE
In "Periodizzazione scavo" altro: IndexError: list index out of range 

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#11]
Traceback (most recent call last):
  File "C:/--/--\pyarchinit-master\tabs\Periodizzazione.py", line 304, in on_pushButton_sort_pressed
    self.MAPPER_TABLE_CLASS, self.ID_TABLE)
  File "C:/--/--\pyarchinit-master\modules\db\pyarchinit_db_manager.py", line 935, in query_sort
    filter_params = self.type_order + "(" + self.table_class + "." + self.order_params[0] + ")"
IndexError: list index out of range

**Comment by slarosa** [comment]
Dovrebbe essere sistemato nella master. Puoi confermare? @enzococca ?

**Comment by slarosa** [comment]
dovrebbe trattarsi della stessa cosa descritta nella issue #9

**Comment by enzococca** [comment]
quindi si può chiudere
