### ISSUE TITLE
Errore nel lancio del matrix

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#119]
Con QGis 3.4.4. 
Alllego il messaggio di errore

2019-01-28T11:49:00     WARNING    Traceback (most recent call last):
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 2161, in on_pushButton_export_matrix_pressed
              data_plot = dlg.generate_matrix()
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Interactive_matrix.py", line 145, in generate_matrix
              data_plotting = matrix_exp.export_matrix()
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\pyarchinit_matrix_exp.py", line 81, in export_matrix
              stderr=err)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 709, in __init__
              errread, errwrite) = self._get_handles(stdin, stdout, stderr)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 1021, in _get_handles
              p2cread = self._make_inheritable(p2cread)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 1071, in _make_inheritable
              _winapi.DUPLICATE_SAME_ACCESS)
             OSError: [WinError 6] Handle non valido

**Comment by MicheleFait** [comment]
2019-01-28T13:41:18     WARNING    Traceback (most recent call last):
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 2161, in on_pushButton_export_matrix_pressed
              data_plot = dlg.generate_matrix()
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Interactive_matrix.py", line 145, in generate_matrix
              data_plotting = matrix_exp.export_matrix()
              File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\pyarchinit_matrix_exp.py", line 81, in export_matrix
              stderr=err)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 709, in __init__
              errread, errwrite) = self._get_handles(stdin, stdout, stderr)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 1021, in _get_handles
              p2cread = self._make_inheritable(p2cread)
              File "C:\OSGeo4W\apps\Python37\lib\subprocess.py", line 1071, in _make_inheritable
              _winapi.DUPLICATE_SAME_ACCESS)
             OSError: [WinError 6] Handle non valido
