### ISSUE TITLE
Errore dopo aggiornamento sqlite

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#125]
Copioincollo il messaggio di errore comparso dopo aver premuto il tasto "update sqlite"

Si è verificato un errore durante l'esecuzione del codice Python: 

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) use DROP TABLE to delete table mediaentity_view [SQL: 'DROP VIEW mediaentity_view;'] (Background on this error at: http://sqlalche.me/e/e3q8) 
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: use DROP TABLE to delete table mediaentity_view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\gui\pyarchinitConfigDialog.py", line 400, in on_pushButton_upd_sqlite_pressed
    if RestoreSchema(db_url,view_file8_4).restore_schema()== False:
  File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\db_createdump.py", line 70, in restore_schema
    raise e
  File "C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\db_createdump.py", line 66, in restore_schema
    conn.execute(text(raw_schema))
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\sql\elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) use DROP TABLE to delete table mediaentity_view [SQL: 'DROP VIEW mediaentity_view;'] (Background on this error at: http://sqlalche.me/e/e3q8)

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
Versione di QGIS: 3.4.4-Madeira Madeira, 73c31df831 

Percorso Python:
C:\Users\Michele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\Michele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:/OSGeo4W/apps/qgis/./python
C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python37.zip
C:\OSGeo4W\apps\Python37\DLLs
C:\OSGeo4W\apps\Python37\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python37
C:\OSGeo4W\apps\Python37\lib\site-packages
C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Michele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master

**Comment by enzococca** [comment]
fix it!
