### ISSUE TITLE
Images_directory_export.py: sqlite3.OperationalError: no such column: mediaentity_view.id_media_thumb

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#158]
Si è verificato un errore durante l'esecuzione del codice Python: 

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: mediaentity_view.id_media_thumb [SQL: 'SELECT mediaentity_view.id_media_thumb AS mediaentity_view_id_media_thumb, mediaentity_view.id_media AS mediaentity_view_id_media, mediaentity_view.filepath AS mediaentity_view_filepath, mediaentity_view.path_resize AS mediaentity_view_path_resize, mediaentity_view.entity_type AS mediaentity_view_entity_type, mediaentity_view.id_media_m AS mediaentity_view_id_media_m, mediaentity_view.id_entity AS mediaentity_view_id_entity \nFROM mediaentity_view \nWHERE mediaentity_view.id_entity = ? AND mediaentity_view.entity_type = ?'] [parameters: (2, 'US')] (Background on this error at: http://sqlalche.me/e/e3q8) 
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: mediaentity_view.id_media_thumb

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Images_directory_export.py", line 141, in on_pushButton_exp_icons_pressed
    search_images_res = self.DB_MANAGER.query_bool(search_dict, 'MEDIAVIEW')
  File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_manager.py", line 793, in query_bool
    res = eval(query_str)
  File "", line 1, in 
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 2843, in all
    return list(self)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: mediaentity_view.id_media_thumb [SQL: 'SELECT mediaentity_view.id_media_thumb AS mediaentity_view_id_media_thumb, mediaentity_view.id_media AS mediaentity_view_id_media, mediaentity_view.filepath AS mediaentity_view_filepath, mediaentity_view.path_resize AS mediaentity_view_path_resize, mediaentity_view.entity_type AS mediaentity_view_entity_type, mediaentity_view.id_media_m AS mediaentity_view_id_media_m, mediaentity_view.id_entity AS mediaentity_view_id_entity \nFROM mediaentity_view \nWHERE mediaentity_view.id_entity = ? AND mediaentity_view.entity_type = ?'] [parameters: (2, 'US')] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by enzococca** [comment]
Stai usando un db vecchio o hai installatobuno nuovo? Prova a fare update
sqlite dalla finestra di configurazione di pyarchinit [bottone in basso a
sinistra]

Il giorno Mar 19 Feb 2019, 15:51 Luca Mandolesi <notifications@github.com>
ha scritto:

**Comment by pyarchinit** [comment]
Il database è quello interno di pyArchInit che usiamo da anni. Ho fatto update ma non ha aggiornato.

**Comment by pyarchinit** [comment]
Impostazione errata della view. Se il medesimo problema si verifica, cliccare in pallenno configurazioni il tasto SQLITE UPDATE 

![immagine](https://user-images.githubusercontent.com/1929829/53167757-2b2c2700-35d9-11e9-871f-8ccff84ce75b.png)
