### ISSUE TITLE
Scheda Documentazione - problema esportazione PDF

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#18]
Non funzionava già sotto alla 2.18, tutto il sistema è da rivedere.

Esportazione PDF sia in formato lista che in formato scheda:

```

Traceback (most recent call last):
  File "C:\Users\Luca\Documents\GitHub\pyarchinit_218\pyarchinit\pyarchinit_Documentazione_mainapp.py", line 294, in on_pushButton_exp_scheda_doc_pressed
    data_list = self.generate_list_pdf()
  File "C:\Users\Luca\Documents\GitHub\pyarchinit_218\pyarchinit\pyarchinit_Documentazione_mainapp.py", line 227, in generate_list_pdf
    res_us_doc = self.DB_MANAGER.select_us_doc_from_db_sql(sito, tipo_doc, nome_doc)
  File "C:\Users\Luca\Documents\GitHub\pyarchinit_218\pyarchinit\modules\db\pyarchinit_db_manager.py", line 1122, in select_us_doc_from_db_sql
    res = self.engine.execute(sql_query_string)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1651, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 709, in execute
    return self._execute_text(object, multiparams, params)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 858, in _execute_text
    statement, parameters
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 927, in _execute_context
    context)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 920, in _execute_context
    context)
  File "C:\OSGeo4W\apps\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such column: tipo_doc u"SELECT * FROM pyunitastratigrafiche WHERE scavo_s = 'Sito archeologico' AND tipo_doc = 'Prospetto' AND nome_doc = 'prospetto'" ()
```

**Comment by slarosa** [comment]
@pyarchinit  A me da l'errore con questa query:
```sql
SELECT * FROM pyarchinit_us_negative_doc WHERE sito_n = 'Castellare, Sovicille, Si' AND  tipo_doc_n = 'Sezione' AND nome_doc_n = ''
```
ma perchè effettivamente la tabella ```pyarchinit_us_negative_doc``` non è presente nel DB.

**Comment by pyarchinit** [comment]
E' tutto un po' da rivedere il sistema.
