### ISSUE TITLE
Modifica schede US

### ISSUE THREAD

**Issue by antoniodambrosio** [pyarchinit/pyarchinit#222]
Quando si modifica una scheda US e la si salva, viene a crearsi un errore, l'errore si verifica al secondo salvataggio. Di seguito l'errore.
2020-03-31T15:01:21     WARNING    Traceback (most recent call last):
              File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 2589, in on_pushButton_save_pressed
              "Il record e' stato modificato. Vuoi salvare le modifiche?",QMessageBox.Ok | QMessageBox.Cancel))
              File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4313, in update_if
              self.MAPPER_TABLE_CLASS, self.ID_TABLE)
              File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\pyarchinit_db_manager.py", line 1029, in query_sort
              filter_params = self.type_order + "(" + self.table_class + "." + self.order_params[0] + ")"
             IndexError: string index out of range

**Comment by antoniodambrosio** [comment]
risolto
