### ISSUE TITLE
QUANTIFICAZIONI SCHEDA INVENTARIO MATERIALI NON FUNZIONA

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#237]
Buongiorno,
se provo ad impostare la "Quantificazione" all'interno della scheda "Inventario Materiali", impostato il criterio di ordinamento, quando premo il bottone Quantifica mi da il seguente errore python:

2020-06-09T08:58:18     WARNING    Traceback (most recent call last):
              File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 436, in on_pushButtonQuant_pressed
              Uw.writerows(csv_dataset)
              File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\csv_writer.py", line 66, in writerows
              self.writerow(row)
              File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\csv_writer.py", line 56, in writerow
              data = data.decode("utf-8")
             AttributeError: 'str' object has no attribute 'decode'

**Comment by enzococca** [comment]
fixed
