### ISSUE TITLE
Errore connessione al DB se non presente

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#248]
Se si è connessi ad un DB e all'apertura quel DB non è raggiungibile, il plugin non viene caricato.
Provare o a fare in modo che il plugin si carichi lo stesso e permetta di accedere al pannello di configurazione, oppure che si connetta ad un DB sqlite presente nella cartella (segnalandolo con un messaggio) oppure creando un DB di default (Segnalandolo).

**Comment by pyarchinit** [comment]
Se si elimina il file di configurazione, viene riportato il seguente errore:

2020-11-02T15:23:48     CRITICAL    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
              cursor.execute(statement, parameters)
             sqlite3.OperationalError: near "MULTIPOLYGON": syntax error
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\__init__.py", line 182, in classFactory
              from .pyarchinitPlugin import PyArchInitPlugin
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\pyarchinitPlugin.py", line 32, in 
              from .pyarchinitDockWidget import PyarchinitPluginDialog
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\pyarchinitDockWidget.py", line 30, in 
              from .tabs.Archeozoology import pyarchinit_Archeozoology
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Archeozoology.py", line 51, in 
              from ..modules.db.pyarchinit_db_manager import Pyarchinit_db_management
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_manager.py", line 41, in 
              from modules.db.pyarchinit_db_mapper import US, UT, SITE, PERIODIZZAZIONE, \
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_mapper.py", line 67, in 
              from modules.db.structures.pyunitastratigrafiche import pyunitastratigrafiche
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\structures\pyunitastratigrafiche.py", line 12, in 
              class pyunitastratigrafiche:
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\structures\pyunitastratigrafiche.py", line 44, in pyunitastratigrafiche
              metadata.create_all(engine)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\schema.py", line 4005, in create_all
              tables=tables)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1940, in _run_visitor
              conn._run_visitor(visitorcallable, element, **kwargs)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1549, in _run_visitor
              **kwargs).traverse_single(element)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
              return meth(obj, **kw)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 757, in visit_metadata
              _is_metadata_operation=True)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
              return meth(obj, **kw)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 791, in visit_table
              include_foreign_key_constraints=include_foreign_key_constraints
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
              return meth(self, multiparams, params)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 68, in _execute_on_connection
              return connection._execute_ddl(self, multiparams, params)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1009, in _execute_ddl
              compiled
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
              exc_info
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
              reraise(type(exception), exception, tb=exc_tb, cause=cause)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
              raise value.with_traceback(tb)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
              cursor.execute(statement, parameters)
             sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "MULTIPOLYGON": syntax error [SQL: '\nCREATE TABLE pyunitastratigrafiche (\n\tgid INTEGER NOT NULL, \n\tarea_s INTEGER, \n\tscavo_s TEXT, \n\tus_s INTEGER, \n\tstratigraph_index_us INTEGER, \n\ttipo_us_s TEXT, \n\trilievo_originale TEXT, \n\tdisegnatore TEXT, \n\tdata TEXT, \n\ttipo_doc TEXT, \n\tnome_doc TEXT, \n\tcoord TEXT, \n\tthe_geom geometry(MULTIPOLYGON,-1), \n\tPRIMARY KEY (gid), \n\tCONSTRAINT "ID_us_unico_s" UNIQUE (gid)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
             
2020-11-02T15:25:18     CRITICAL    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
              cursor.execute(statement, parameters)
             sqlite3.OperationalError: near "MULTIPOLYGON": syntax error
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\__init__.py", line 182, in classFactory
              from .pyarchinitPlugin import PyArchInitPlugin
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\pyarchinitPlugin.py", line 32, in 
              from .pyarchinitDockWidget import PyarchinitPluginDialog
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\pyarchinitDockWidget.py", line 30, in 
              from .tabs.Archeozoology import pyarchinit_Archeozoology
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Archeozoology.py", line 51, in 
              from ..modules.db.pyarchinit_db_manager import Pyarchinit_db_management
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_manager.py", line 41, in 
              from modules.db.pyarchinit_db_mapper import US, UT, SITE, PERIODIZZAZIONE, \
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_mapper.py", line 67, in 
              from modules.db.structures.pyunitastratigrafiche import pyunitastratigrafiche
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\structures\pyunitastratigrafiche.py", line 12, in 
              class pyunitastratigrafiche:
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\structures\pyunitastratigrafiche.py", line 44, in pyunitastratigrafiche
              metadata.create_all(engine)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\schema.py", line 4005, in create_all
              tables=tables)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1940, in _run_visitor
              conn._run_visitor(visitorcallable, element, **kwargs)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1549, in _run_visitor
              **kwargs).traverse_single(element)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
              return meth(obj, **kw)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 757, in visit_metadata
              _is_metadata_operation=True)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
              return meth(obj, **kw)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 791, in visit_table
              include_foreign_key_constraints=include_foreign_key_constraints
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
              return meth(self, multiparams, params)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 68, in _execute_on_connection
              return connection._execute_ddl(self, multiparams, params)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1009, in _execute_ddl
              compiled
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
              exc_info
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
              reraise(type(exception), exception, tb=exc_tb, cause=cause)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
              raise value.with_traceback(tb)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
              context)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
              cursor.execute(statement, parameters)
             sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "MULTIPOLYGON": syntax error [SQL: '\nCREATE TABLE pyunitastratigrafiche (\n\tgid INTEGER NOT NULL, \n\tarea_s INTEGER, \n\tscavo_s TEXT, \n\tus_s INTEGER, \n\tstratigraph_index_us INTEGER, \n\ttipo_us_s TEXT, \n\trilievo_originale TEXT, \n\tdisegnatore TEXT, \n\tdata TEXT, \n\ttipo_doc TEXT, \n\tnome_doc TEXT, \n\tcoord TEXT, \n\tthe_geom geometry(MULTIPOLYGON,-1), \n\tPRIMARY KEY (gid), \n\tCONSTRAINT "ID_us_unico_s" UNIQUE (gid)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
