### ISSUE TITLE
SCHEDA SITO - GENERAZIONE NUOVE SCHEDE - Errore Tuple index out of range

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#259]

**Comment by pyarchinit** [comment]
Sono su un DB postgres "vecchio".
Dalle configurazioni non mi viene richiesto aggiornamento.
Potrebbero esserci campi diversi tra la nuova versione e quella vecchia della scheda US.

Manca qualche query in pyarchinit_DB_update?

![immagine](https://user-images.githubusercontent.com/1929829/98909218-d1ad0f80-24c1-11eb-8179-4ed4406f617c.png)



 Traceback (most recent call last):
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Site.py", line 1053, in on_pushButton_genera_us_pressed
              str(self.comboBox_t_us.currentText()))
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_manager.py", line 1424, in insert_arbitrary_number_of_us_records
              '', '', '', '', '', '', '', '', '', None, None, '', '[]','[]', '[]', '[]', '[]','','','','',None,None,'','','','','','','[]','[]',None,None,None,None,None,None,None,None,None,None,'','','','','','','','','','',None,None,None,'','','','','','','','')
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\db\pyarchinit_db_manager.py", line 269, in insert_values
              arg[96],
             IndexError: tuple index out of range
