### ISSUE TITLE
PROBLEMI CON LA VIEW DELLA SCHEDA INDIVIDUO VERSIONE 2.0.6 E 2.0.9 (BRENCH)

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#295]
Ho riempito due record della scheda individuo (vedi esempio sotto)
![scheda_individuo](https://user-images.githubusercontent.com/10104718/99886139-853c9f00-2c3a-11eb-87b2-bc3b8274ec54.JPG)

A questo punto ho fatto un "cerca" e "trova" per vedere se fa la selezione ed è tutto ok.
Dopo di che, attivo il GIS viewer e faccio una nuova ricerca ed ottengo questo errore:
IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Schedaind.py", line 1656, in on_pushButton_search_go_pressed
    id_us_list = self.charge_id_us_for_individuo()
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Schedaind.py", line 2045, in charge_id_us_for_individuo
    data_list_id_us.append(data_list_us[us][0].id_us)
IndexError: list index out of range

NON HO CAPITO SE SBAGLIO A COMPILARE LA SCHEDA

**Comment by montarob** [comment]
PROBLEMA RISOLTO CON IL BRENCH 2.0.1
