### ISSUE TITLE
Errore caricamento plugin dopo aggiornamento

### ISSUE THREAD

**Issue by DavidePagl** [pyarchinit/pyarchinit#316]
buonasera,
dopo aver aggiornato il plugin mi restituisce il seguente errore. Ho anche disinstallato e reinstallato il plugin (amministratore). anche riavviando qgis il problema persiste. Vi ringrazio antcipatamente.
Davide Pagliarosi

**Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory()** 

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "POINT": syntax error [SQL: CREATE TABLE pyarchinit_siti ( id INTEGER NOT NULL, sito_nome TEXT, the_geom geometry(POINT,-1), PRIMARY KEY (id), UNIQUE (id) ) ] (Background on this error at: http://sqlalche.me/e/e3q8) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "POINT": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 229, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitPlugin.py", line 32, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitDockWidget.py", line 30, in 
    from .tabs.Archeozoology import pyarchinit_Archeozoology
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Archeozoology.py", line 51, in 
    from ..modules.db.pyarchinit_db_manager import Pyarchinit_db_management
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\pyarchinit_db_manager.py", line 44, in 
    from modules.db.pyarchinit_db_mapper import US, UT, SITE, PERIODIZZAZIONE, \
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\pyarchinit_db_mapper.py", line 81, in 
    from modules.db.structures.pysito_point import pysito_point
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\structures\pysito_point.py", line 12, in 
    class pysito_point:
  File "C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\structures\pysito_point.py", line 34, in pysito_point
    metadata.create_all(engine)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\schema.py", line 4321, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 2058, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1627, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 826, in visit_table
    include_foreign_key_constraints,  # noqa
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1046, in _execute_ddl
    compiled,
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "POINT": syntax error
[SQL: 
CREATE TABLE pyarchinit_siti (
	id INTEGER NOT NULL, 
	sito_nome TEXT, 
	the_geom geometry(POINT,-1), 
	PRIMARY KEY (id), 
	UNIQUE (id)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.5-A Coruña A Coruña, 984615fe1e 

Percorso Python:
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\Users\Davide\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LandSurveyCodesImport
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
C:/Users/Davide/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Video_UAV_Tracker
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\Davide\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by enzococca** [comment]
É la prima volta che installavi pyarchinit? Avevi una versione già
installata?

Prova a spostare il db pyarchinit_db.sqlite (che si trva in
pyarchinit/pyarchinit_DB_folder) in una altra cartella e riavvia qgis.

Fa sapere
E

Il mar 22 dic 2020, 18:19 DavidePagl <notifications@github.com> ha scritto:

**Comment by DavidePagl** [comment]
ciao Enzo.
si avevo già una versione installata con diversi DB. Seguendo il tuo suggerimento si è ripristinato tutto! Grazie mille!

**Comment by enzococca** [comment]
Bene
Chiudi la iusse.

E

Il mar 22 dic 2020, 20:47 DavidePagl <notifications@github.com> ha scritto:
