### ISSUE TITLE
SCHEDA REPERTI: errore Nuovo record

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#354]
SCHEDA REPERTI: se si clicca su Nuovo record appare questo errore
2021-01-07T17:18:22     WARNING    Traceback (most recent call last):
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Inv_Materiali.py", line 1496, in on_pushButton_new_rec_pressed
              self.numero_reperto()
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Inv_Materiali.py", line 1126, in numero_reperto
              contatore = int(self.DATA_LIST[i].n_reperto)
             TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
			 
			 Accalappiare l'errore e mettere i numero max nr rep + 1 se repertato è Si, oppure mettere numero 0

**Comment by enzococca** [comment]
aggiornare db
