### ISSUE TITLE
Scheda Reperti - Creazione nuovo record

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#363]
db nuovo, sito creato. Record 1, inserito il numero inventario salvo e mi dà errore

2021-01-30T17:24:30 WARNING Traceback (most recent call last):
File "C:/Users/Giuppy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1469, in on_pushButton_new_rec_pressed
self.numero_reperto()
File "C:/Users/Giuppy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1120, in numero_reperto
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

appena digito un qualsiasi carattere nel campo repertato dà errore, anche se non thesaurus ho inserito valorisì/no
2021-01-30T17:27:49 WARNING Traceback (most recent call last):
File "C:/Users/Giuppy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1469, in on_pushButton_new_rec_pressed
self.numero_reperto()
File "C:/Users/Giuppy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1120, in numero_reperto
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by enzococca** [comment]
Credo che tu abbia operato su un db non allineato. Quale versione di pyarchinit usi?
Prova ad aggiornare il db
