### ISSUE TITLE
ERRORE ESPORTAZIONE PDF - SCHEDA REPERTI - V. 2.3.0 (DB AGGIORNATO)

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#379]
Quando vado a fare le varie esportazioni in pdf dentro la scheda inventario materiali ottengo questo errore python:

TypeError: ' 
Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1691, in on_pushButton_print_pressed
    data_list = self.generate_el_casse_pdf(sito_ec)
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Inv_Materiali.py", line 1921, in generate_el_casse_pdf
    elenco_casse_list.sort()
TypeError: '

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.6-A Coruña A Coruña, ec80021f49 

Percorso Python:
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\Users\rober\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master
.
F:/LARGO_GRAMSCI

**Comment by montarob** [comment]
ERRORE RISOLTO.
In pratica avevo importato nel pannel layer la scheda inventario_materiali_table e all'interno della Tabella Attributi, avevo disattivato dei campi tra cui il campo "Cassa_nr" attraverso lo strumento "Organizza Colonne". In pratica riattivando tutti i campi non dà più problemi e fa correttamente l'esportazione.
