### ISSUE TITLE
ERRORE SCHEDA REPERTI - V.1.1.13  - OSError: Cannot open resource ""  - fileName='' identity=[ImageReader@0x2738bf08400]

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#380]
2021-02-22T14:49:06     WARNING    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 667, in open_for_read
              return open_for_read_by_name(name,mode)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 611, in open_for_read_by_name
              return open(name,mode)
             FileNotFoundError: [Errno 2] No such file or directory: ''
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 670, in open_for_read
              return getBytesIO(datareader(name) if name[:5].lower()=='data:' else urlopen(name).read())
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 222, in urlopen
              return opener.open(url, data, timeout)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 510, in open
              req = Request(fullurl, data)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 328, in __init__
              self.full_url = url
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 354, in full_url
              self._parse()
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 383, in _parse
              raise ValueError("unknown url type: %r" % self.full_url)
             ValueError: unknown url type: ''
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\tabs\Inv_Materiali.py", line 1688, in on_pushButton_print_pressed
              US_pdf_sheet.build_Finds_sheets(data_list)
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\utility\pyarchinit_exp_Findssheet_pdf.py", line 2141, in build_Finds_sheets
              elements.append(single_finds_sheet.create_sheet())
              File "C:\Users\Luca\Programmazione\pycharm_pj\pyarchinit\modules\utility\pyarchinit_exp_Findssheet_pdf.py", line 178, in create_sheet
              logo.drawHeight = 1.5 * inch * logo.drawHeight / logo.drawWidth
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\platypus\flowables.py", line 489, in __getattr__
              self._setup_inner()
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\platypus\flowables.py", line 450, in _setup_inner
              img = self._img
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\platypus\flowables.py", line 483, in __getattr__
              self._img = ImageReader(self._file)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 825, in __init__
              annotateException('\nfileName=%r identity=%s'%(fileName,self.identity()))
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 1406, in annotateException
              rl_reraise(t,v,b)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 144, in rl_reraise
              raise v
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 789, in __init__
              self.fp = open_for_read(fileName,'b')
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\reportlab\lib\utils.py", line 672, in open_for_read
              raise IOError('Cannot open resource "%s"' % name)
             OSError: Cannot open resource ""
             fileName='' identity=[ImageReader@0x2738bf08400]

**Comment by pyarchinit** [comment]
DB UTILIZZATO: database generato dal plugin stesso ex novo.

**Comment by enzococca** [comment]
devi settare la path per il per il logo. aggiungerò un warning

**Comment by pyarchinit** [comment]
Metti la path al logo di pyarchiint. Poi uno se vuole la sostituisce.

**Comment by enzococca** [comment]
fatto. Prova a esportare tutte le schede di tutti i form e fammi sapere
