### ISSUE TITLE
SCHEDA CAMPIONI 2.4.4. = OSError: Cannot open resource "" fileName='' identity=[ImageReader@0x1d0c8a03ba8] 

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#400]
Durante l'esportazione della scheda campioni v. 2.4.4. ottengo questo errore; Tuttavia poi lui fa cmq l'esportazione correttamente sia dell'elenco campioni che delle schede campioni.

OSError: Cannot open resource "" fileName='' identity=[ImageReader@0x1d0c8a03ba8] 
Traceback (most recent call last):
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 658, in open_for_read
    return open_for_read_by_name(name,mode)
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 602, in open_for_read_by_name
    return open(name,mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 661, in open_for_read
    return getBytesIO(datareader(name) if name[:5].lower()=='data:' else urlopen(name).read())
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 510, in open
    req = Request(fullurl, data)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\tabs\Campioni.py", line 1117, in on_pushButton_exp_champ_sheet_pdf_pressed
    Champ_pdf_sheet.build_Champ_sheets(data_list)
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\modules\utility\pyarchinit_exp_Campsheet_pdf.py", line 1046, in build_Champ_sheets
    elements.append(single_Campioni_sheet.create_sheet())
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\modules\utility\pyarchinit_exp_Campsheet_pdf.py", line 169, in create_sheet
    logo.drawHeight = 1.5 * inch * logo.drawHeight / logo.drawWidth
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\platypus\flowables.py", line 494, in __getattr__
    self._setup_inner()
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\platypus\flowables.py", line 455, in _setup_inner
    img = self._img
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\platypus\flowables.py", line 488, in __getattr__
    self._img = ImageReader(self._file)
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 816, in __init__
    annotateException('\nfileName=%r identity=%s'%(fileName,self.identity()))
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 1397, in annotateException
    rl_reraise(t,v,b)
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 150, in rl_reraise
    raise v
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 780, in __init__
    self.fp = open_for_read(fileName,'b')
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\reportlab\lib\utils.py", line 663, in open_for_read
    raise IOError('Cannot open resource "%s"' % name)
OSError: Cannot open resource ""
fileName='' identity=[ImageReader@0x1d0c8a03ba8]

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.6-A Coruña A Coruña, ec80021f49

**Comment by enzococca** [comment]
Controlla la path per il logo

Il ven 5 mar 2021, 09:38 montarob <notifications@github.com> ha scritto:

**Comment by montarob** [comment]
Settando la path del logo non dà più errori
