### ISSUE TITLE
Esportazione matrix

### ISSUE THREAD

**Issue by antoniodambrosio** [pyarchinit/pyarchinit#414]
"Permissin denied"
PermissionError: [Errno 13] Permission denied: 'Harris_matrix_16_3_2021_16_6_30' 
Traceback (most recent call last):
  File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\tabs\US_USM.py", line 3233, in on_pushButton_export_matrix_pressed
    data_plot = dlg.generate_matrix()
  File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\tabs\Interactive_matrix.py", line 343, in generate_matrix
    data_plotting = matrix_exp.export_matrix
  File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\modules\utility\pyarchinit_matrix_exp.py", line 211, in export_matrix
    f = open(filename, "w")
PermissionError: [Errno 13] Permission denied: 'Harris_matrix_16_3_2021_16_6_30'

Ho provato a cancellare tutti i vecchi files dentro alla cartella Matrix folder di pyarchinit, ho creato i periodi e ho dato i codici periodo correttamente, penso che il problema non sia questo. Non riesco a capire cosa possa essere, ho aperto QGIS da amministratore e dal C:

**Comment by antoniodambrosio** [comment]
RISOLTO, modifica nello script

**Comment by enzococca** [comment]
Chiudi tutte le iusse risolte

grazie

Il mar 16 mar 2021, 17:40 antoniodambrosio ***@***.***> ha
scritto:
