### ISSUE TITLE
Esportazioni immagini

### ISSUE THREAD

**Issue by antoniodambrosio** [pyarchinit/pyarchinit#416]
Non riesco ad esportare le immagini, mi dà questo tipo di errore, ho impostato tutte le path dallo spinotto ma evidentemente c'è qualcosa che faccio in maniera errata.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bronco\\pyarchinit\\pyarchinit_image_resize\\None' 
Traceback (most recent call last):
  File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\tabs\Images_directory_export.py", line 193, in on_pushButton_exp_icons_pressed
    self.OS_UTILITY.copy_file_img(thumb_resize_str+str(sing_media.path_resize), sing_US_path)
  File "C:/Users/bronco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\modules\utility\pyarchinit_OS_utility.py", line 47, in copy_file_img
    shutil.copy(file_path, destination)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bronco\\pyarchinit\\pyarchinit_image_resize\\None'

**Comment by enzococca** [comment]
Perché non esiste una path che sia C:\Users\bronco\pyarchinit\
pyarchinit_image_resize\None

Controlla bene come hai settato la path

Il mer 17 mar 2021, 17:41 antoniodambrosio ***@***.***> ha
scritto:

**Comment by antoniodambrosio** [comment]
Ciao Enzo, può dipendere dal fatto che quella cartella è stata creata ex novo ed è stata messa all'interno di pyarchinit?

**Comment by enzococca** [comment]
Che vuoi dire? Tu puoi dargli qualsiasi path tu voglia. Hai solo scritto
male la path

Il gio 18 mar 2021, 15:28 antoniodambrosio ***@***.***> ha
scritto:

**Comment by antoniodambrosio** [comment]
La path non l'ho scritta, ho selezionato la cartella e me l'ha scritta automaticamente, continuo a non capire dove sia l'errore
