### ISSUE TITLE
ERRORE ESPORTAZIONE SCHEDA DOCUMENTAZIONE 2.5.3

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#421]
Quando vado a stampare l'elenco documentazione mi dà questo errore:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "area": syntax error [SQL: SELECT * FROM pyunitastratigrafiche WHERE scavo_s = 'Rimini(RN) Via delle Officine 47' AND tipo_doc = 'Pianta' AND nome_doc = 'Tavola 2: Posizionamento dell'area di indafine e delle trincee effettuate su CTR'] (Background on this error at: http://sqlalche.me/e/e3q8) 
Traceback (most recent call last):
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1284, in _execute_context
    statement,
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    do_commit_twophase().  Its format is unspecified.
sqlite3.OperationalError: near "area": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\tabs\Documentazione.py", line 512, in on_pushButton_exp_elenco_doc_pressed
    data_list = self.generate_list_pdf()
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\tabs\Documentazione.py", line 407, in generate_list_pdf
    res_us_doc = self.DB_MANAGER.select_us_doc_from_db_sql(sito, tipo_doc, nome_doc)
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-pyarchiti2EM\modules\db\pyarchinit_db_manager.py", line 1487, in select_us_doc_from_db_sql
    res = self.engine.execute(sql_query_string)
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 2244, in execute
    def _execute_compiled(self, compiled, multiparams, params):
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1012, in execute
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1187, in _execute_text
    self, dialect, constructor, statement, parameters, *args
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1324, in _execute_context
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1518, in _handle_dbapi_exception
    if self._is_disconnect:
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    # that out.
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1284, in _execute_context
    statement,
  File "C:\Users\rober\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    do_commit_twophase().  Its format is unspecified.
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "area": syntax error
[SQL: SELECT * FROM pyunitastratigrafiche WHERE scavo_s = 'Rimini(RN) Via delle Officine 47' AND tipo_doc = 'Pianta' AND nome_doc = 'Tavola 2: Posizionamento dell'area di indafine e delle trincee effettuate su CTR']
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by montarob** [comment]
LA DESCRIZIONE DELLE TAVOLE NON VA NEL CAMPO "NOME_DOC", DOVE INVECE SI DEVE INDICARE SOLO IL NOME DELLA TAVOLA (ES. TAVOLA 1), BENSì NELLE NOTE!
