### ISSUE TITLE
PROBLEMI INSTALLAZIONE PYARCHINIT SU QGIS 3.18

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#428]
INSTALLANDO DA REPOSITORY MI DA' QUESTO PROBLEMA

2021-05-07T11:46:29     CRITICAL    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
              __import__(packageName)
              File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/IlariaFerrando/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 128, in
              install_libraries.append(p[0])
             IndexError: list index out of range

**Comment by enzococca** [comment]
Controlla che non ci sia un altro pyarchinit installato perché va in
conflitto. Inoltre la path mi sembra sbagliata. Prova a cancellare e
reinstallare.

Il ven 7 mag 2021, 12:06 montarob ***@***.***> ha scritto:
