### ISSUE TITLE
problema nell'importazione tabella table_us da sqlite a sqlite

### ISSUE THREAD

**Issue by colonnellomariachi** [pyarchinit/pyarchinit#434]
Durante il corso pyarchinit, mentre stavamo vedendo l'importazione da un db sqlite all'altro, mi genera un errore alla fine della importazione della table_us (allego Screenshot)
![SharedScreenshot](https://user-images.githubusercontent.com/6452448/120692967-b8dd6900-c4a8-11eb-8b7e-efea371966af.jpg)
. Se poi provo ad aprire la Scheda US mi genera il seguente log di python

2021-06-03T19:38:44     WARNING    Traceback (most recent call last):
              File "C:/Users/Marco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 2556, in set_sito
              self.DATA_LIST_REC_TEMP = self.DATA_LIST_REC_CORR = self.DATA_LIST[0] ####darivedere
             IndexError: list index out of range
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/Marco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitPlugin.py", line 1007, in runUS
              pluginGui = pyarchinit_US(self.iface)
              File "C:/Users/Marco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 813, in __init__
              self.set_sito()
              File "C:/Users/Marco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 2574, in set_sito
              QMessageBox.information(self, "Warning" , "There is no such site: "'"'+ str(site_set_str) +'"'" in this tab, Please disable the 'site choice' from the plugin configuration tab to see all records or create the tab",QMessageBox.Ok)
             NameError: name 'site_set_str' is not defined

**Comment by enzococca** [comment]
Prova a settare un sito prima e vedi se ti da lo stesso errore. Ad ogni
modo Setta "ignore" e non abort quando trasferisci i dati.

Fa sapere
E

Il gio 3 giu 2021, 20:17 colonnellomariachi ***@***.***> ha
scritto:
