### ISSUE TITLE
ERRORE INSTALLAZIONE V. 3.9.12

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#453]
ModuleNotFoundError: No module named 'pyarchinit-3' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyarchinit-3'

**Comment by montarob** [comment]
Errore mio...era la vesrione sbagliata
