### ISSUE TITLE
Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory() 

### ISSUE THREAD

**Issue by gabcicc** [pyarchinit/pyarchinit#517]
Versione QGIS 3.22 LTR,
Pyarchinit 4.3.4
MacOS Monterey 12.5.1 (Apple M1)

All'installazione del Plug-in mi da il seguente problema: 

Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory() 

ImportError: cannot import name '_fitz' from partially initialized module 'fitz' (most likely due to a circular import) (/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/fitz/__init__.py) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 243, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitPlugin.py", line 28, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitDockWidget.py", line 31, in 
    from .tabs.Gis_Time_controller import pyarchinit_Gis_Time_Controller
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/Gis_Time_controller.py", line 38, in 
    from .US_USM import pyarchinit_US
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/US_USM.py", line 32, in 
    from pdf2docx import parse
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/pdf2docx/__init__.py", line 1, in 
    from .converter import Converter
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/pdf2docx/converter.py", line 7, in 
    import fitz
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/fitz/__init__.py", line 10, in 
    from fitz.fitz import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/fitz/fitz.py", line 15, in 
    from . import _fitz
ImportError: cannot import name '_fitz' from partially initialized module 'fitz' (most likely due to a circular import) (/Users/g.ciccone/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs/fitz/__init__.py)

Versione Python: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Versione di QGIS: 3.22.4-Białowieża Białowieża, 3f4577ce6e

**Comment by enzococca** [comment]
prova con questa nuova versione 4.3.8 e fammi sapere

**Comment by gabcicc** [comment]
Enzo la 4.3.8 funziona perfettamente su QGIS 3.28.2-Firenze, quindi ottimo. Problema risolto!


Per completezza ti dico invece che non funziona sulla Long Term Release QGIS, dove mi da il seguente errore: 

Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory() 

ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libprotobuf.22.dylib'   Referenced from: '/Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-38-darwin.so'   Reason: tried: '/opt/Qt/5.14.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.14.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file)

**Comment by enzococca** [comment]
Credo sia un errore di opencv-python, prova ad aggiornarlo e riavvia qgis

Il sab 21 gen 2023, 12:58 gabcicc ***@***.***> ha scritto:
