### ISSUE TITLE
ERRORE: Matplotlib Python package not found

### ISSUE THREAD

**Issue by 0mc0l** [pyarchinit/pyarchinit#530]
Buongiorno a tutti,
per lavoro devo scaricare il plugin _giswater_ 3.5 su QGis 3.22, l'ho scaricato tramite link e installato senza intoppi. 
Il primo problema che sussiste è il fatto che il plugin non compaia nella barra degli strumenti, il secondo è che al riavvio di QGis compare una finestra di errore con dicitura che lascio di seguito.

Chiedo gentilmente se qualcuno sappia risolverlo. 
premetto che ho già provato a disinstallarlo e scaricare una versione più e meno recente dello stesso plugin, ma la situazione non cambia.
Ringrazio in anticipo!

ERRORE:

Matplotlib Python package not found. Do you want to install Matplotlib?

Impossibile caricare il plugin 'giswater' a causa di un errore chiamando il metodo classFactory() 

FileNotFoundError: [Errno 2] No such file or directory: 'python' 
Traceback (most recent call last):
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/toolbars/om/profile_button.py", line 30, in 
    import matplotlib.pyplot as plt
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/pyplot.py", line 36, in 
    import matplotlib.colorbar
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/colorbar.py", line 44, in 
    import matplotlib.contour as contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/contour.py", line 17, in 
    import matplotlib.text as text
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/text.py", line 16, in 
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/textpath.py", line 11, in 
    from matplotlib.mathtext import MathTextParser
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/mathtext.py", line 27, in 
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in 
    from . import _imaging as core
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 0x0002): Library not loaded: '/opt/X11/lib/libxcb.1.dylib'
  Referenced from: '/Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so'
  Reason: tried: '/opt/X11/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/__init__.py", line 32, in classFactory
    from .main import Giswater
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/main.py", line 17, in 
    from .core.admin.admin_btn import GwAdminButton
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/admin/admin_btn.py", line 30, in 
    from .gis_file_create import GwGisFileCreate
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/admin/gis_file_create.py", line 11, in 
    from ..utils import tools_gw
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/utils/tools_gw.py", line 42, in 
    from ..load_project_menu import GwMenuLoad
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/load_project_menu.py", line 17, in 
    from .toolbars import buttons
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/toolbars/buttons.py", line 19, in 
    from .om.profile_button import GwProfileButton
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/toolbars/om/profile_button.py", line 34, in 
    subprocess.run(["python", "-m", "ensurepip"])
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

Versione Python: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Versione di QGIS: 3.22.16-Białowieża Białowieża, 6f08e4d7b0 

Percorso Python:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python
.
/Users/pippi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/giswater/core/ui/..

**Comment by enzococca** [comment]
Ciao, non ho capito se hai un problema con il plugin giswater o pyarchinit.
Nel primo caso non posso aiutarti perché non é un nostro plugin. Ad ogni
modo matplotlib é una libreria nativa von qgis. Che versione hai di qgis?

Il mar 14 mar 2023, 14:36 0mc0l ***@***.***> ha scritto:

**Comment by 0mc0l** [comment]
La versione è la 3.22.16

**Comment by 0mc0l** [comment]
> Ciao, non ho capito se hai un problema con il plugin giswater o pyarchinit. Nel primo caso non posso aiutarti perché non é un nostro plugin. Ad ogni modo matplotlib é una libreria nativa von qgis. Che versione hai di qgis? Il mar 14 mar 2023, 14:36 0mc0l ***@***.***> ha scritto:
> […](#)

La versione è la 3.22.16

**Comment by enzococca** [comment]
Il problema riguarda pyarchinit?

**Comment by 0mc0l** [comment]
> Il problema riguarda pyarchinit?

No, il messaggio di errore compare ogni volta che apro o riavvio QGis
