### ISSUE TITLE
Errore python installazione pyarchinit Mac

### ISSUE THREAD

**Issue by AndrMrb98** [pyarchinit/pyarchinit#572]
subprocess.CalledProcessError: Command '['pip3', 'install', 'openai']' died with

**Comment by enzococca** [comment]
Ciao! Posta tutto l'errore per favore. Inoltre indica che versione di mac
stai usando.
Molte cose cambiano da versione a versione del mac
E

Il mar 31 ott 2023, 18:02 AndrMrb98 ***@***.***> ha scritto:

**Comment by AndrMrb98** [comment]
Ciao! La versione è Mac Ventura 13.2. L'errore è il seguente (E' indicata anche la versione di Qgis): 

subprocess.CalledProcessError: Command '['pip3', 'install', 'openai']' died with . 
Traceback (most recent call last):
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/modules/utility/askgpt.py", line 5, in 
    import openai
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 243, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitPlugin.py", line 28, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitDockWidget.py", line 31, in 
    from .tabs.Gis_Time_controller import pyarchinit_Gis_Time_Controller
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/Gis_Time_controller.py", line 36, in 
    from .US_USM import pyarchinit_US
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/US_USM.py", line 50, in 
    from ..modules.utility.askgpt import MyApp
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andreamorabito/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/modules/utility/askgpt.py", line 13, in 
    subprocess.check_call(["pip3", "install", "openai"],shell = False )
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip3', 'install', 'openai']' died with .


Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b53397

**Comment by AndrMrb98** [comment]
Salve,
Mi scusi per il ritardo nella risposta, tra oggi e domani proverò e le farò
sapere. Grazie mille per la disponibilità.
A presto.

A.M.

Il giorno ven 8 dic 2023 alle ore 04:49 enzo ***@***.***> ha
scritto:
