### ISSUE TITLE
PROBLEMA ESPORTAZIONE PDF SCHEDE US ED ELENCO V. 4.6.2

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#573]
Buongiorno,
ho provato ad esportare le schede e l'elenco US in pdf ma mi da questo errore:
Traceback (most recent call last):
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4428, in on_pushButton_print_pressed
    data_list = self.generate_list_pdf()
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4170, in generate_list_pdf
    quote.sort()
TypeError: '

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.32.3-Lima Lima, 67d46100b5 

FACCIO PRESENTE CHE HO QUESTO PROBLEMA SOLTANTO CON QUESTO SPECIFICO DATABASE.

**Comment by montarob** [comment]
Ho provato a creare un altro database e ad importarci dentro le varie schede e i vettori tramite il tool di importazione. Se importo solo le schede e poi provo ad esportare in pdf non ho problemi, appena importo pure le geometrie mi da quel problema postato in precedenza.

**Comment by enzococca** [comment]
hai risolto?

**Comment by montarob** [comment]
Problema risolto
