### ISSUE TITLE
PROBLEMA INSTALLAZIONE PYARCHINIT V. 6.6.3

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#577]
Ho disabilitato il plugin e lo ho aggiornato alla nuova versione 4.6.3; mi dice plugin installato con successo ma quando vado ad attivarlo mi dà questo errore e non si attiva:
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "MULTIPOLYGON": syntax error [SQL: CREATE TABLE pyunitastratigrafiche ( gid INTEGER NOT NULL, area_s INTEGER, scavo_s TEXT, us_s INTEGER, stratigraph_index_us INTEGER, tipo_us_s TEXT, rilievo_originale TEXT, disegnatore TEXT, data TEXT, tipo_doc TEXT, nome_doc TEXT, coord TEXT, the_geom geometry(MULTIPOLYGON,-1), unita_tipo_s TEXT, PRIMARY KEY (gid), CONSTRAINT "ID_us_unico_s" UNIQUE (gid) ) ] (Background on this error at: https://sqlalche.me/e/14/e3q8) 
Traceback (most recent call last):
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "MULTIPOLYGON": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 264, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitPlugin.py", line 28, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitDockWidget.py", line 29, in 
    from .tabs.Deteta import pyarchinit_Deteta
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Deteta.py", line 34, in 
    from ..modules.db.pyarchinit_db_manager import Pyarchinit_db_management
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\pyarchinit_db_manager.py", line 44, in 
    from modules.db.pyarchinit_db_mapper import US, UT, SITE, PERIODIZZAZIONE, POTTERY, \
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\pyarchinit_db_mapper.py", line 85, in 
    from modules.db.structures.pyunitastratigrafiche import pyunitastratigrafiche
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\structures\pyunitastratigrafiche.py", line 12, in 
    class pyunitastratigrafiche:
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\db\structures\pyunitastratigrafiche.py", line 45, in pyunitastratigrafiche
    metadata.create_all(engine)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 3110, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\ddl.py", line 846, in visit_metadata
    self.traverse_single(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\ddl.py", line 890, in visit_table
    self.connection.execute(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\sql\ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs\sqlalchemy\engine\default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "MULTIPOLYGON": syntax error
[SQL: 
CREATE TABLE pyunitastratigrafiche (
	gid INTEGER NOT NULL, 
	area_s INTEGER, 
	scavo_s TEXT, 
	us_s INTEGER, 
	stratigraph_index_us INTEGER, 
	tipo_us_s TEXT, 
	rilievo_originale TEXT, 
	disegnatore TEXT, 
	data TEXT, 
	tipo_doc TEXT, 
	nome_doc TEXT, 
	coord TEXT, 
	the_geom geometry(MULTIPOLYGON,-1), 
	unita_tipo_s TEXT, 
	PRIMARY KEY (gid), 
	CONSTRAINT "ID_us_unico_s" UNIQUE (gid)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.34.1-Prizren Prizren, 133927424d

**Comment by montarob** [comment]
Ho installato una versione orecedente di pyarchinit e poi aggiornato di nuovo il plugin da repository dentro QGIS e si è installato con successo!
