### ISSUE TITLE
TypeError: 'NoneType' object is not iterable` Export schede US

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#61]
Ciao,
quando provo ad esportare le schede US mi da questo errore.

`2018-10-21T14:20:08     WARNING    Traceback (most recent call last):
              File "C:/Users/Giuse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 1127, in on_pushButton_pdf_exp_pressed
              US_pdf_sheet.build_US_sheets(data_list)
              File "C:/Users/Giuse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\pyarchinit_exp_USsheet_pdf.py", line 1370, in build_US_sheets
              elements.append(single_us_sheet.create_sheet_archeo3_usm_fields())
              File "C:/Users/Giuse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\modules\utility\pyarchinit_exp_USsheet_pdf.py", line 834, in create_sheet_archeo3_usm_fields
              for i in eval(self.col_legante):
             TypeError: 'NoneType' object is not iterable`

**Comment by enzococca** [comment]
Sembrerebbe che questo campo non deve essere vuoto. Prova esportarlo
riempito

Il Dom 21 Ott 2018, 14:28 Giuseppe Guarino <notifications@github.com> ha
scritto:
