### ISSUE TITLE
Errori all'apertura su QGIS 3.36

### ISSUE THREAD

**Issue by MicGeos** [pyarchinit/pyarchinit#621]
2024-04-06T09:36:38     WARNING    Traceback (most recent call last):
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitPlugin.py", line 926, in runSite
              pluginGui = pyarchinit_Site(self.iface)
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Site.py", line 217, in __init__
              self.msg_sito()
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Site.py", line 1041, in msg_sito
              dlg.charge_list()
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\gui\pyarchinitConfigDialog.py", line 3925, in charge_list
              sito_vl = self.UTILITY.tup_2_list_III(self.DB_MANAGER.group_by('site_table', 'sito', 'SITE'))
             AttributeError: 'str' object has no attribute 'group_by'

**Comment by enzococca** [comment]
Ciao, quale versione di pyarchinit stai usando?

Il sab 6 apr 2024, 09:43 MicGeos ***@***.***> ha scritto:

**Comment by MicGeos** [comment]
Pyarchinit 4.7.0 su QGIS 3.36.1

**Comment by enzococca** [comment]
Prova a scaricarlo di nuovo e reinstallalo. Perché ho fatto dei cambiamenti
senza cambiare versione. Infatti quel tuo problema lo avevo risolto

Il sab 6 apr 2024, 12:22 MicGeos ***@***.***> ha scritto:

**Comment by MicGeos** [comment]
Il plugin pyarchinit si installa, ma la maschera sito dà l'errore. Pyarchinit è l'ultimo modificato (scaricato da code)



2024-04-06T13:39:56     WARNING    Traceback (most recent call last):
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\pyarchinitPlugin.py", line 926, in runSite
              pluginGui = pyarchinit_Site(self.iface)
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Site.py", line 217, in __init__
              self.msg_sito()
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\Site.py", line 1041, in msg_sito
              dlg.charge_list()
              File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\gui\pyarchinitConfigDialog.py", line 3925, in charge_list
              sito_vl = self.UTILITY.tup_2_list_III(self.DB_MANAGER.group_by('site_table', 'sito', 'SITE'))
             AttributeError: 'str' object has no attribute 'group_by'

**Comment by enzococca** [comment]
Prova cancellare il file cinfig.cfg nella cartella pyarchinit_DB_folder e
riavvia qgis

Il sab 6 apr 2024, 13:43 MicGeos ***@***.***> ha scritto:

**Comment by enzococca** [comment]
Immagino che sia la prima volta che installi pyarchinit, giusto?. Per
verificare l errore mandami in privato un link zoom che vediamo insieme il
problema.
***@***.***

Il lun 8 apr 2024, 09:53 MicGeos ***@***.***> ha scritto:
