### ISSUE TITLE
Errore apertura: Pyarchinit non si carica su QGis

### ISSUE THREAD

**Issue by MicGeos** [pyarchinit/pyarchinit#623]
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato 
Traceback (most recent call last):
  File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 125, in 
    import cv2
  File "C:\PROGRA~1/QGIS3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'cv2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS3.36.2/apps/qgis/./python\qgis\utils.py", line 404, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 129, in 
    subprocess.call(['pip', 'install', 'opencv-python','--user'])
  File "C:\PROGRA~1\QGIS3.36.2\apps\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS3.36.2\apps\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS3.36.2\apps\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

Versione Python: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.36.2-Maidenhead Maidenhead, 6d250527

**Comment by enzococca** [comment]
Ciao questo succede perché tieni installato due versioni di opencv-python.
Bisognerebbe che tu disintalli opencv-python e poi riavvi qgis.

Per disinstallare dovresti aprire il terminale di qgis (se usi osgeo é il
file .bat che trovi appena pri la cartella in C di osgeow4) altrimenti
cerca dove tieni installato qgis. Aperto il terminale di qgis digita
python -m pip uninstall opencv-python --user

Dovrebbe disinstallare.
Se riscontri problemi fa sapere. Altrimenti contattami in privato

Il mar 30 apr 2024, 10:29 MicGeos ***@***.***> ha scritto:
