### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Folgore001** [pyarchinit/pyarchinit#627]
subprocess.CalledProcessError: Command '['C:\\PROGRA~1\\QGIS33~1.9\\bin\\python-qgis.bat', '-m', 'pip', 'install', 'python-docx==1.1.2']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "C:\Users/maria/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 125, in 
    self.thread.started.connect(lambda: self.worker.install_packages(selected_packages))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/maria/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 71, in install_packages
    install(package)
  File "C:\Users/maria/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\__init__.py", line 186, in install
    subprocess.run([python_executable, "-m", "pip", "install", shlex_quote(package)],
  File "C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\PROGRA~1\\QGIS33~1.9\\bin\\python-qgis.bat', '-m', 'pip', 'install', 'python-docx==1.1.2']' returned non-zero exit status 1.

**Comment by enzococca** [comment]
Ciao, se hai problemi con l'installazione che qgis stai usando( se
standalone o osgeo) e come riproduci questo errore se non riesco ad
aiutarti

Il lun 29 lug 2024, 02:13 Folgore001 ***@***.***> ha scritto:
