### ISSUE TITLE
Scheda Sito - problema durante ordinamento records

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#9]
Problema generale con le finestre per ordinare i recor. Quando si apre e si chiude una finestra dal tasto  rosso con la x appare il seguente errore:

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users\Luca\Documents\GitHub\pyarchinit\tabs\Site.py", line 279, in on_pushButton_sort_pressed
    self.MAPPER_TABLE_CLASS, self.ID_TABLE)
  File "C:\Users\Luca\Documents\GitHub\pyarchinit\modules\db\pyarchinit_db_manager.py", line 935, in query_sort
    filter_params = self.type_order + "(" + self.table_class + "." + self.order_params[0] + ")"
IndexError: list index out of range

**Comment by enzococca** [comment]
quindi si può chiudere
